baseurl = "https://jasb.netlify.app/"
math = true
title = "just another stats blog"
author = "@Fabian Class"
copyright = "Copyright © 2020, @Fabian Class"
canonifyurls = true
paginate = 3

theme = "hugo-blog-jeffprod"


[taxonomies]
    tag = "tags"
    archive = "archives"
